export const LEVELS = [
  {
    level: 0,
    faixa: 'FAIXA BRANCA',
    color: '#e4e4e7',
    textColor: '#71717a',
    description: 'Não executou nenhuma ação de vendas',
    requirement: null,
  },
  {
    level: 1,
    faixa: 'FAIXA AZUL',
    color: '#3b82f6',
    textColor: '#ffffff',
    description: 'Enviou 10 propostas de orçamento ou fechou o primeiro contrato',
    requirement: 'Envie 10 propostas ou comprove o primeiro contrato fechado',
  },
  {
    level: 2,
    faixa: 'FAIXA VERDE 5K',
    color: '#22c55e',
    textColor: '#ffffff',
    description: '5 MIL RECEBIDO ou 10 MIL CONTRATADO em até 30 dias',
    requirement: 'Comprove R$ 5.000 recebidos ou R$ 10.000 contratados em 30 dias',
    minReceived: 5000,
    minContracted: 10000,
  },
  {
    level: 3,
    faixa: 'FAIXA VERDE 10K',
    color: '#16a34a',
    textColor: '#ffffff',
    description: '10 MIL RECEBIDO ou 20 MIL CONTRATADO em até 30 dias',
    requirement: 'Comprove R$ 10.000 recebidos ou R$ 20.000 contratados em 30 dias',
    minReceived: 10000,
    minContracted: 20000,
  },
  {
    level: 4,
    faixa: 'FAIXA LARANJA 15K',
    color: '#ff3b03',
    textColor: '#ffffff',
    description: '15 MIL RECEBIDO ou 30 MIL CONTRATADO em até 30 dias',
    requirement: 'Comprove R$ 15.000 recebidos ou R$ 30.000 contratados em 30 dias',
    minReceived: 15000,
    minContracted: 30000,
  },
  {
    level: 5,
    faixa: 'FAIXA LARANJA 20K',
    color: '#d93000',
    textColor: '#ffffff',
    description: '20 MIL RECEBIDO ou 40 MIL CONTRATADO em até 30 dias',
    requirement: 'Comprove R$ 20.000 recebidos ou R$ 40.000 contratados em 30 dias',
    minReceived: 20000,
    minContracted: 40000,
  },
  {
    level: 6,
    faixa: 'FAIXA MARROM 40K',
    color: '#92400e',
    textColor: '#ffffff',
    description: '40 MIL RECEBIDO ou 80 MIL CONTRATADO em até 30 dias',
    requirement: 'Comprove R$ 40.000 recebidos ou R$ 80.000 contratados em 30 dias',
    minReceived: 40000,
    minContracted: 80000,
  },
  {
    level: 7,
    faixa: 'FAIXA PRETA 80K',
    color: '#18181b',
    textColor: '#ffffff',
    description: '80 MIL RECEBIDO ou 160 MIL CONTRATADO em até 30 dias',
    requirement: 'Comprove R$ 80.000 recebidos ou R$ 160.000 contratados em 30 dias',
    minReceived: 80000,
    minContracted: 160000,
  },
]

export function getLevelInfo(level: number) {
  return LEVELS[level] ?? LEVELS[0]
}
